name: "Emojify PR Title"
description: "All PRs start with an emoji"
inputs:
  github-token:
    description: "The GitHub authentication token"
    required: true
    default: ${{ github.token }}
  emoji-list:
    descriptions: "JSON of emojis available for random selection"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "cloud-lightning"
  color: "purple"
