on: [pull_request]

jobs:
  emojify-pr-title:
    runs-on: ubuntu-latest
    name: emojify pr title - test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: emojify step
        uses: ./